# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
service:
  port: 80
image:
  repository: searge
  tag: "v0.1.6-5a35aa5"
  os: linux
  arch: amd64
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN
